
#ifndef _MAIN_H
#define _MAIN_H

#define SSID_MAXLENGTH (64)
#define WIFIPW_MAXLENGTH (32)
#define SIOT_UID_MAXLENGTH (32)
#define SIOT_DEVKEY_MAXLENGTH (48)

#define EEPROM_WRITE
#define EEPROM_HEADER_KEY (0b1111001011011100100101010111111000111010110101011000101000101101)
#define EEPROM_HEADER_ADDR (0)
#define EEPROM_SSID_ADDR (EEPROM_HEADER_ADDR + sizeof(uint64_t))
#define EEPROM_WIFIPW_ADDR (EEPROM_SSID_ADDR + SSID_MAXLENGTH)
#define EEPROM_SIOT_UID_ADDR (EEPROM_WIFIPW_ADDR + WIFIPW_MAXLENGTH)
#define EEPROM_SIOT_DEVKEY_ADDR (EEPROM_SIOT_UID_ADDR + SIOT_UID_MAXLENGTH)
#define EEPROM_TEMP_SLOT_ADDR (EEPROM_SIOT_DEVKEY_ADDR + SIOT_DEVKEY_MAXLENGTH)
#define EEPROM_HUMID_SLOT_ADDR (EEPROM_TEMP_SLOT_ADDR + sizeof(uint8_t))
#define EEPROM_LIGHT_SLOT_ADDR (EEPROM_HUMID_SLOT_ADDR + sizeof(uint8_t))
#define EEPROM_WATER_SLOT_ADDR (EEPROM_LIGHT_SLOT_ADDR + sizeof(uint8_t))
#define EEPROM_LED_CTRL_SLOT_ADDR (EEPROM_WATER_SLOT_ADDR + sizeof(uint8_t))
#define EEPROM_PUMP1_CTRL_SLOT_ADDR (EEPROM_LED_CTRL_SLOT_ADDR + sizeof(uint8_t))
#define EEPROM_PUMP2_CTRL_SLOT_ADDR (EEPROM_PUMP1_CTRL_SLOT_ADDR + sizeof(uint8_t))
#define EEPROM_TOTAL_BYTES (EEPROM_PUMP2_CTRL_SLOT_ADDR + sizeof(uint8_t))

#endif